name: Test Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * SUN'

jobs:

  test:
    strategy:
      matrix:
        version: [ 1.15.x, 1.14.x, 1.13.x ]
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Golang
        if: success()
        uses: actions/setup-go@main
        with:
          version: ${{ matrix.version }}
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          go test -v -covermode=count ./...
